### ISSUE TITLE
Import Error when trying to run mergerfs.balance

### ISSUE THREAD

**Issue by spikked27** [desertwitch/mergerFS-unRAID#1]
When trying to run mergerfs.balance I get the following error, any help is appreciated!

`root@PurpleCloud:~# mergerfs.balance -p 75  /mnt/addons/Frigate_Recordings 
Traceback (most recent call last): File "/usr/bin/mergerfs.balance", line 18, in <module> import ctypes File "/usr/lib64/python3.9/ctypes/__init__.py", line 8, in <module> from _ctypes import Union, Structure, Array ImportError: libffi.so.7: cannot open shared object file: No such file or directory`

**Comment by desertwitch** [comment]
Solved on forums (dependency problem unrelated to the plugin)
